# Generated by Django 5.2.1 on 2025-05-13 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s3_file_path', models.CharField(max_length=1024)),
                ('description', models.TextField()),
            ],
        ),
    ]
